//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicoleProvanFinalExam
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Customer_Detail
    {
        public int DetailId { get; set; }
        public int CustNum { get; set; }
        public string CustUserName { get; set; }
        public string CustPassword { get; set; }

        public virtual Customer Customer { get; set; }




        public static Boolean IsCheckCredentials(string username, string password)
        {
            using (var context = new FinalExamEntities())
            {
                var query = context.Customer_Detail.Where(user => user.CustUserName == username).FirstOrDefault<Customer_Detail>();

                var query2 = context.Customer_Detail.Where(user => user.CustPassword == password).FirstOrDefault<Customer_Detail>();

                if (query != null && query2 != null)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }

        public static int GetId(string username)
        {
            using (var context = new FinalExamEntities())
            {

                var query = from user in context.Customer_Detail
                            where user.CustUserName == username
                            select user.CustNum;

                int id = query.FirstOrDefault();

                return id;
            }
        }

        public static string CreatePassword(string firstName, string lastName)
        {
            string container = "";

            /*get letters from first name that are in 
            positions that are divisible by 2*/
            for (int i = 0; i < firstName.Length; i++)
            {
                if (i % 2 == 0)
                {
                    container += firstName[i];
                }
            }



            //reverse order of lastName 
            int length = lastName.Length - 1;
            string reverse = "";

            while (length >= 0)
            {
                reverse += lastName[length];
                length--;
            }


            //get last three letters of last name
            string lastThree = "";

            for (int i = 0; i < 3; i++)
            {
                lastThree += reverse[i];

            }

            string password = container + lastThree;

            return password;
        }


        public static void AddDetail(string firstName, string lastName)
        {
            using (var context = new FinalExamEntities())
            {

                var query = from user in context.Customers
                            where user.CustFirstName == firstName
                            select user.CustNum;

                int id = query.FirstOrDefault();

                string username = lastName;

                string password = CreatePassword(firstName, lastName);



                Customer_Detail newDet = new Customer_Detail()
                {
                    CustNum = id,
                    CustUserName = username,
                    CustPassword = password
                };

                context.Customer_Detail.Add(newDet);
                context.SaveChanges();

                Console.WriteLine($"Your username is {username}");
                Console.WriteLine($"Your password is {password}");


            }
        }
    }
}
