//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicoleProvanFinalExam
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }

        public int SalesNum { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<bool> Filled { get; set; }
        public Nullable<int> CustNum { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }



        public static void NewSale(int id)
        {

            DateTime today = DateTime.Today;

            using (var context = new FinalExamEntities())
            {


                Sale sale = new Sale()
                {
                    SalesDate = today,
                    Filled = false,
                    CustNum = id

                };

                context.Sales.Add(sale);
                context.SaveChanges();
            }
        }
    }
}
