//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicoleProvanFinalExam
{
    using System;
    using System.Linq;
    using System.Collections.Generic;

    public partial class SalesInvoice
    {
        public int InvoiceId { get; set; }
        public int SalesNum { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }

        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }

        public static void NewSaleInvoice(int id, int quantity, string desc)
        {


            using (var context = new FinalExamEntities())
            {
                var salesNum = context.Sales.Where(user => user.CustNum == id).Select(user => user.SalesNum).FirstOrDefault();
                var prodNum = context.Products.Where(user => user.Descr == desc).Select(user => user.ProductNum).FirstOrDefault();
                var price = context.Products.Where(user => user.Descr == desc).Select(user => user.MSRP).FirstOrDefault();


                SalesInvoice invoice = new SalesInvoice()
                {
                    SalesNum = salesNum,
                    ProductNum = prodNum,
                    Quantity = quantity,
                    SalesPrice = price * quantity

                };

                context.SalesInvoices.Add(invoice);
                context.SaveChanges();
            }
        }
    }
}
